apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "xdmod.fullname" . }}
  labels:
    {{- include "xdmod.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "xdmod.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "xdmod.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "xdmod.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: xdmod-config
          persistentVolumeClaim:
            claimName: xdmod-config
        - name: xdmod-database
          persistentVolumeClaim:
            claimName: xdmod-database
        - name: xdmod-munge
          secret:
            secretName: xdmod-munge
            defaultMode: 0400
        - name: xdmod-slurm
          configMap:
            name: xdmod-slurm-configmap
            defaultMode: 0755
            items:
            - key: slurm.conf
              path: slurm.conf
      initContainers:
        - name: {{ .Chart.Name }}-init
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          command: ["cp", "-R", "-u", "-p", "/etc/xdmod/.", "/etc/xdmod-mounted"]
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - mountPath: "/etc/xdmod-mounted/"
              name: xdmod-config

      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
            - mountPath: "/etc/xdmod"
              name: xdmod-config
            - mountPath: "/var/lib/mysql"
              name: xdmod-database
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}

        - name: slurm-collector
          securityContext:
            {{- toYaml .Values.slurm_collector.securityContext | nindent 12 }}
          image: "{{ .Values.slurm_collector.image.repository }}:{{ .Values.slurm_collector.image.tag }}"
          imagePullPolicy: {{ .Values.slurm_collector.image.pullPolicy }}
          command: ["/usr/bin/run-munge"]
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: "/etc/munge/munge.key"
              name: xdmod-munge
              subPath: munge.key
            - name: xdmod-slurm
              mountPath: /etc/slurm/slurm.conf
              subPath: slurm.conf
          env:
            {{- range $key, $value := .Values.slurm_collector.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
